apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp # name of the deployment
  labels:
    app: backend-restapp # label for the deployment
    # tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-restapp
# --------------------------------------------------------
  template:             # this is the template for the pod
    metadata:
      labels:
        app: backend-restapp
        # tier: backend
    spec:
      containers:
      - name: backend-restapp-container
        image: stacksimplify/kube-helloworld:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: "300m"
          limits:
            memory: 512Mi
            cpu: "500m"

# If you wish to have one sidecar container tehn this block will liik like this
      # - name: sidecar-container-eg-istio
      #   image: x0ox0ox0ox0ox0/=-0=-0=-0=-0=-0=-0=-0
      #   ports:
      #   - containerPort: xxx
      #   resources:
      #     requests:
      #       memory: ---Mi
      #       cpu: "---m"
      #     limits:
      #       memory: ---Mi
      #       cpu: "---m"
