# Tells External Secrets Operator: connect to AWS Secrets Manager in ap-south-1,
# authenticate using the ums-app-sa ServiceAccount (which has Pod Identity → IAM role).
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: ums-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: ums-app-sa
