apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulseauth-sa
  namespace: backend-prod
  annotations:
    eks.amazonaws.com/role-arn: PLACEHOLDER_ESO_IRSA_ROLE_ARN
    # Replace with: terraform output -raw eso_irsa_role_arn
