apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulseauth-sa
  namespace: backend-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::183295435445:role/eks-rbac-dev-pulseauth-eso-role
