# ServiceAccount for ums-app pods.
# IRSA: annotation tells ESO which IAM role to assume when using this SA's JWT token.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ums-app-sa
  namespace: ums-app
  labels:
    app: ums-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::183295435445:role/eks-public-dev-ums-app-role
