apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ums-app
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: umsdb
  POSTGRES_USER: umsuser
  POSTGRES_PASSWORD: umspassword
