# Tells External Secrets Operator: connect to AWS Secrets Manager in ap-south-1,
# authenticate using the external-secrets ServiceAccount (IRSA → IAM role).
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: pulseauth
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
