apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-admin-crb
subjects:
- kind: Group
  name: eks-devops-admins       # must match kubernetes_groups in access_entries.tf
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: devops-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
