apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-demo-sa
  namespace: s3-demo
  annotations:
    # Paste from: cd 03_irsa/terraform/env-dev && terraform output iam_role_arn
    eks.amazonaws.com/role-arn: REPLACE_ME