apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulseauth-postgres-external-secret
  namespace: backend-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulseauth-secret-store
    kind: SecretStore
  target:
    name: pulseauth-postgres-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: eks-public-dev/pulseauth/postgres
